// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Jzon from "../node_modules/rescript-jzon/src/Jzon.bs.js";
import * as React from "react";

var experience = Jzon.object4((function (param) {
        return [
                param.start,
                param.title,
                param.end,
                param.description
              ];
      }), (function (param) {
        return {
                TAG: /* Ok */0,
                _0: {
                  start: param[0],
                  end: param[2],
                  title: param[1],
                  description: param[3]
                }
              };
      }), Jzon.field("start", Jzon.string), Jzon.field("title", Jzon.string), Jzon.field("end", Jzon.string), Jzon.field("description", Jzon.string));

var formations = Jzon.object4((function (param) {
        return [
                param.locale,
                param.title,
                param.periodic,
                param.description
              ];
      }), (function (param) {
        return {
                TAG: /* Ok */0,
                _0: {
                  locale: param[0],
                  title: param[1],
                  periodic: param[2],
                  description: param[3]
                }
              };
      }), Jzon.field("locale", Jzon.string), Jzon.field("title", Jzon.string), Jzon.field("periodic", Jzon.string), Jzon.field("description", Jzon.string));

var profile = Jzon.object5((function (param) {
        return [
                param.name,
                param.description,
                param.skills,
                param.experiences,
                param.formations
              ];
      }), (function (param) {
        return {
                TAG: /* Ok */0,
                _0: {
                  name: param[0],
                  description: param[1],
                  skills: param[2],
                  experiences: param[3],
                  formations: param[4]
                }
              };
      }), Jzon.field("name", Jzon.string), Jzon.field("description", Jzon.string), Jzon.field("skills", Jzon.array(Jzon.string)), Jzon.field("experiences", Jzon.array(experience)), Jzon.field("formations", Jzon.array(formations)));

var Codecs = {
  experience: experience,
  formations: formations,
  profile: profile
};

async function getData(param) {
  var response = await fetch("/api/data");
  var profileData = await response.json();
  var json = Jzon.decodeWith(profileData, profile);
  console.log(json);
  return json;
}

function App(Props) {
  var data = getData(undefined);
  console.log(data);
  return React.createElement("div", {
              className: "App"
            }, React.createElement("h1", undefined, "Bom dia"));
}

var make = App;

export {
  Codecs ,
  getData ,
  make ,
}
/* experience Not a pure module */
