// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

async function getData(param) {
  var response = await fetch("/api/data");
  return await response.json();
}

function App(Props) {
  var data = getData(undefined);
  console.log(data);
  return React.createElement("div", {
              className: "App"
            }, React.createElement("h1", undefined, "Bom dia"));
}

var make = App;

export {
  getData ,
  make ,
}
/* react Not a pure module */
